<?php
/**
 * The template for displaying all pages.
 *
 * This is the template that displays all pages by default.
 * Please note that this is the WordPress construct of pages
 * and that other 'pages' on your WordPress site will use a
 * different template.
 *
 * @package storefront
 */

get_header(); ?>

	<div id="primary" class="content-area static-page">
        <div class="container ">
            <h1>Terms &amp; Conditions</h1>
            <h4>Terms of Use</h4>
            <p> Welcome to the Gigalumi website, operated by Global Amiba Network Technology Inc. (“Amiba”) and located at <a href='http://www.Gigalumi.com' target='_blank' class='url'>www.Gigalumi.com</a> (the &quot;Site&quot;). The following terms and conditions (“Terms”) govern your use of the Site.</p>
            <p>By accessing, viewing, or using the content, material, products, or services available on or through the Site, you certify that you have read, understand, and agree to be legally bound by these Terms, as well as our <a href="/privacy-policy/" target="_blank"><strong>Privacy Policy</strong></a>, each of which is incorporated by reference as if fully set forth herein. You further certify that you are 18 years of age or older and that you have all the necessary rights, power and authority to enter into this Agreement and perform the obligations set forth under this Agreement. You understand and agree that your use of the Site or any content, material, products or services made available on or through the Site (collectively, the &quot;Services&quot;) signifies that you fully accept and agree to these Terms of Use.</p>
            <h4>Registration</h4>
            <p>In order to access certain content, material, products or services on the Site, you may be asked to register and create an account. As part of the registration process, you may be asked to click to agree to these Terms, and may then be asked to select or submit a user name and password. You may also be required to provide us with certain information about yourself including some types of personally identifiable information, including your legal name, phone number, address, email address, gender, and age. You are responsible for ensuring that your password and account login are kept secret, safe, and secure at all times. Gigalumi will not be held responsible or liable for any misuse of your account in the event that a third party has access to and uses your password and account login in any way.</p>
            <p>When placing an order through the Site, you will be required to provide other personal information, such as shipping address, billing address, and payment details. Additional information may be collected by Gigalumi or its third party providers at this time for security and anti-fraud purposes. You represent that the personal information you provide to us via the Site is true, valid, complete and up-to-date in all respects, and you confirm that you are the person referred to in the shipping (unless the item is a gift) and billing information provided. Should any of the information you provide on the Site change, please login to your account and update such information directly on the Site.</p>
            <p>Any personal information that you provide to us via the Site is subject to our <a href="/privacy-policy/" target="_blank"><strong>Privacy Policy</strong></a>.</p>
            <h4>Modifications to the service and prices</h4>
            <p>Prices for our products are subject to change without notice.</p>
            <p>We reserve the right at any time to modify or discontinue the Service (or any part or content thereof) without notice at any time.</p>
            <p>We shall not be liable to you or to any third-party for any modification, price change, suspension or discontinuance of the Service.</p>
            <h4>Purchases</h4>
            <p>Some products or services made available through the Site may be available for purchase. By purchasing products or services made available through the Site, you represent that you have reached the age of majority (which in most states is 18 years old) and have the legal capacity to enter into a contract. If you are under the age of majority or cannot lawfully enter into a contract, you must have your parent or guardian review these Terms and the <a href="/privacy-policy/" target="_blank"><strong>Privacy Policy</strong></a>, and register or place an order on your behalf. Gigalumi may use a third party payment processor to process credit card transactions made through the Site. You are also responsible for paying any governmental taxes imposed in connection with use of the Site or the purchase or any products or services made available through the Site, including sales, use, and excise taxes (excluding only taxes on Gigalumi’s net income). To the extent that Gigalumi is obligated to collect such taxes, the applicable tax will be added to your billing account. All sales are subject to our shipping and return policies, which shall be made available to you on the Site or other delivered to you with your purchased goods. All refunds are in Gigalumi’s sole discretion.</p>
            <h4>Transactions</h4>
            <p>We reserve the right at any time after receipt of your order to accept or decline your order, or any portion thereof, even after your receipt of an order confirmation. We reserve the right, at our sole discretion, to limit the quantity of items purchased and/or to prohibit sales to dealers. In the event that a product is listed at an incorrect price, we shall have the right to refuse or cancel orders placed for the product listed at the incorrect price, regardless of whether the order has been confirmed and/or your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, we will promptly issue a credit to your credit card account in the amount of the incorrect price.</p>
            <h4>General Restrictions on Use</h4>
            <p>You agree to use the Site and the Services only for purposes that are permitted by these Terms of Use and in compliance with all applicable laws, regulations, and generally accepted practices or guidelines in the relevant jurisdictions. You may only use the Site and Services for your non-commercial, non-exclusive, non-assignable, non-transferable and limited personal use, and for no other purposes.</p>
            <p>You will not (and will not attempt to):</p>
            <ul>
            <li>Access any of the Services by any means other than through the interface that is provided by Gigalumi;</li>
            <li>Gain unauthorized access to Gigalumi’s computer system or engage in any activity that interferes with the performance of, or impairs the functionality or security of the Site, the Services, Gigalumi’s networks and computer systems;</li>
            <li>Access any of the Site or the Services through any automated means or with any automated features or devices (including use of scripts or web crawlers);</li>
            <li>Access or collect any personally identifiable information, including any names, email addresses or other such information for any purpose, including, without limitation, commercial purposes;</li>
            <li>Reproduce, duplicate, copy, sell, trade, or resell any aspect of the Site or the Services for any purpose; and</li>
            <li>Reproduce, duplicate, copy, sell, trade or resell any products or services bearing any trademark, service mark, trade name, logo or service mark owned by Gigalumi in a way that is likely or intended to cause confusion about the owner or authorized user of such marks, names or logos.</li>

            </ul>
            <h4>Content</h4>
            <p>As between you and Gigalumi, Gigalumi owns or licenses all information and materials, including logos, designs, titles, phrases, product names, images, illustrations, icons, photographs, and the copyrights, trademarks, service marks, trade dress, and other intellectual property rights associated therewith, in or made available through the Site (“Site Content”), as well as the selection, coordination, arrangement, and organization and enhancement of the Site Content. All Site Content is protected pursuant to copyright, trademark, patent, and other applicable laws. You agree not to remove or alter any copyright notice or any other proprietary notice on any Site Content. As between you and Gigalumi, all names, trademarks, symbols, slogans, or logos appearing on the Site are proprietary to Gigalumi or its affiliates, licensors, or suppliers. Use or misuse of these trademarks is expressly prohibited and may violate federal and state trademark law. Under no circumstances will you have any rights of any kind in or to the Site Content, other than the right to use the Site Content in accordance with these Terms.</p>
            <p>Certain features of the Site may allow you to contribute feedback and other information to the Site for access, use, viewing, and commentary by other users of the Site (collectively, “Comments”). By posting Comments, you represent that you have the full legal right to provide the Comments and that use of the Comments by Gigalumi on the Site, and all other persons and entities, will not: (a) infringe any intellectual property rights of any person or entity or any rights of publicity, personality, or privacy of any person or entity, including as a result of your failure to obtain consent to post personally identifying or otherwise private information about a person; (b) violate any law, statute, ordinance, regulation, or agreement; or (c) constitute disclosure of any confidential information owned by any third party. Upon your submission of Comments or other material or information to Gigalumi, you grant Gigalumi a worldwide, perpetual, irrevocable, transferable, license to access, use, distribute, reproduce, display, modify, create derivative works based upon, and sublicense the Comments, all without any compensation to you whatsoever. For avoidance of doubt, Gigalumi shall be under no obligation: (1) to maintain any Comments in confidence; (2) to compensate you in any way for your Comments; or (3) to respond to any Comments. </p>
            <h4>Errors, Inaccuracies, and Omissions</h4>
            <p>Occasionally there may be information on the Site that contains typographical errors, inaccuracies, or omissions that may relate to product descriptions, pricing, promotions, offers, and availability. We reserve the right to correct any errors, inaccuracies or omissions and to change or update information or cancel orders if any information on the Site is inaccurate at any time without prior notice (including after you have submitted your order). We cannot and do not review all communications, products, or services made available on or through the Site, but, although not obligated to, may review, verify, make changes to or remove any Comments, Site Content, or the Site, including information submitted in connection with the Site Content or other features at any time, with or without notice in our sole discretion.</p>
            <h4>Disclaimers and Warranties</h4>
            <p>Gigalumi reserves the right to change the assortment of items offered and to limit the quantity of items that may be purchased from time to time and at any time, without prior notice. We also reserve the right to alter the terms or duration of any special offers or sale promotion. Gigalumi is not liable in case of stock outage or unavailability of products. We have made every effort to display as accurately as possible the colors of our products that appear at the Site, but we cannot guarantee that your computer monitor&#39;s display of any color will be accurate.</p>
            <p>Gigalumi expressly disclaims, to the fullest extent permitted by law, any express or implied warranties: (i) that the Site, Services, Site Content, goods, advice, information or links provided on the Site will meet your requirements; (ii) that the Services will be uninterrupted, timely, secure or free from error; (iii) that defects in the operation or functionality of any software provided to you as part of the Services will be corrected; (iv) regarding the Site Content, goods, services, advice, information or links provided by any third parties or users; (v) that the Site, Site Content, goods, services, advice, or information displayed on the Site will meet your requirements; and (vi) that the Site will be error-free or that any errors will be corrected. No advice or information, whether oral or written, obtained by you from the Site shall create any warranty not expressly stated in these Terms.</p>
            <p>You understand that the technical processing and transmission of any Site Content and Comments may be transferred unencrypted and involve transmissions over various networks and changes to conform and adapt to technical requirements of connecting networks or devices. Please be advised that we do not guarantee that any information sent to or from our Site will be secure during transmission, nor can we guarantee the confidentiality of any communication or material transmitted to us via the Site or the Internet, including, for example, personal information such as your name or address. Gigalumi assumes no responsibility for: (a) any error, omission, interruption, deletion, defect, delay in operation or transmission, communications line failure, theft or destruction or unauthorized access to, or alteration of, any communication; and (b) any problems or technical malfunction of any telephone network or lines, computer online systems, servers or providers, computer equipment, software, failure of any email or players due to technical problems or traffic congestion on the Internet or on any of the Site, including any injury or damage to you or to any person’s computer related to or resulting from use of the Services or the Site.</p>
            <p>No conditions, warranties or other terms (including any implied terms as to satisfactory quality, fitness for purpose or conformance with description) apply to the Site, Site Content and/or Services except to the extent that they are expressly set out in these Terms.</p>
            <h4>Limitation of Liability</h4>
            <p>IN NO EVENT WILL GIGALUMI BE LIABLE FOR DAMAGES OTHER THAN ACTUAL AND DIRECT DAMAGES PROVEN IN A COURT OF LAW. IN NO EVENT SHALL GIGALUMI’S LIABILITY EXCEED THE PRICE YOU PAID FOR THE PRODUCT OR SERVICE THAT IS THE SUBJECT OF THE CLAIM. IF ANY PART OF THIS LIMITATION OF LIABILITY IS FOUND TO BE INVALID OR UNENFORCEABLE FOR ANY REASON, THEN THE TOTAL LIABILITY OF GIGALUMI AND ITS LICENSORS SHALL NOT EXCEED TEN DOLLARS ($10).</p>
            <p>Without limiting the foregoing, you understand and acknowledge that Gigalumi shall not be liable to you for:</p>
            <ol start='' >
            <li>Any indirect, incidental, consequential, punitive or exemplary losses which may be incurred by you arising out of your use of, or inability to use, the Site or the Services, including any loss of profit (whether incurred directly or indirectly), any loss of goodwill or business reputation, or any loss of data suffered by you; or</li>
            <li>Any loss or damage which may be incurred by you as a result of: (i) any reliance placed by you on the completeness, accuracy or existence of any advertising, or as a result of any relationship or transaction between you and any advertiser or sponsor whose advertising appears on the Site or the Services; (ii) any changes that Gigalumi may make to the Site or Services, or for any permanent or temporary cessation in the provision of the Services (or any features within the Services); (iii) the deletion of, corruption of, unauthorized access to, or failure to store, any content and other communications data maintained or transmitted by or through your use of the Site or the Services; (iv) the use of any products or services obtained on or through the Site; or (v) any other matter relating to the Site, the Services, the Site Content, or the Comments.</li>

            </ol>
            <p>The limitations on Gigalumi’s liability to you in this Section 7 shall apply whether or not Gigalumi has been advised of or should have been aware of the possibility of any such losses arising. </p>
            <p>IF YOU ARE DISSATISFIED WITH THE SITE, THE SERVICES, OR THE TERMS OF USE, YOUR SOLE AND EXCLUSIVE REMEDY IS TO DISCONTINUE USING THE SITE AND SERVICES. </p>
            <h4>Indemnity</h4>
            <p>You agree to defend, indemnify and hold harmless Gigalumi, its officers, directors, members, employees, agents, affiliates, licensors and suppliers, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney’s fees) arising from: (i) your use of and access to the Site and Services; (ii) your violation of any of these Terms, including the <a href="/privacy-policy/" target="_blank"><strong>Privacy Policy</strong></a>; (iii) your violation of any third party rights, including without limitation any copyright, intellectual property, or privacy rights; or (vi) the use by any other persons accessing this Site using your Internet account or account login. This defense and indemnification obligation will survive these Terms and your use of the Site and Services. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you hereunder, and you shall cooperate in all reasonable respects in such defense. You may not settle any claim contemplated in this Section 8 without the prior written consent of Gigalumi.</p>
            <h4>Distribution/Uploading of Third Party Content</h4>
            <p>Any Content you submit or make available for inclusion on the website shall become the sole property of Global Amiba Network Technology Inc.. Regarding all such Content, including, without limitation, creative ideas, suggestions, content, postings, artwork, photograph, material or other submissions (collectively, &quot;User Submissions&quot;), you grant the Company the right to use, reproduce, disclose, publish and distribute any material you submit for any reason without compensation.</p>
            <p>No User Submissions, regardless of how they may be marked, will be received by us in confidence, nor shall they be subject to any express or implied obligation of confidentially. Neither the Company, nor its Affiliates, nor their respective officers, directors, agents or employees shall be liable for any use or disclosure of any User Submissions.</p>
            <p>In addition, the Company may, in our sole discretion, at any time and without prior notice to you, suspend or terminate any public forum, any other portion of the Web Site, or the subscription or registration of any user who violates any of these terms and conditions of use, any of the rules, regulations or guidelines or for any other behavior that we in our sole discretion believe is inappropriate.</p>
            <h4>Links To Other Sites</h4>
            <p>The Site may contain links or references to other websites outside of our control. Links to other websites may use our Site logo or style as a result of a co-branding agreement. These websites may send cookies to you and may collect personally identifiable information about you and make use of that data in ways that this Site would not. Please be aware that Gigalumi has no control over these websites and that these Terms of Use do not apply to any third party sites. Gigalumi cannot be held responsible for those sites or external sources, or for any damage or losses deriving from the use of the content, or goods and services available on those sites or external sources. Gigalumi encourages you to read the <a href="/privacy-policy/" target="_blank"><strong>Privacy Policy</strong></a> and terms of use linked or referenced in the websites you enter.</p>
            <h4>Complaint Procedures</h4>
            <p>If you believe that any content or postings on this Site violates your intellectual property or other rights, please notify Gigalumi by email at <a href='mailto:service@gigalumi.com' target='_blank' class='url'>service@gigalumi.com</a> with a comprehensive detailed message setting forth the following information: (a) your name and the name of your company, if any; (b) your contact information, including your email address; (c) the nature and substance of your complaint, the specific rights at issue, and your basis for making the complaint, including the content or posting that is objectionable; and (d) the following statement: “The statements, representations, and assertions made in this message are true, complete, and accurate and I have the full legal authority to make each and every such statement, representation, and assertion and to make and be granted any demand made in this message.”</p>
        </div>
        
	</div><!-- #primary -->

<?php
do_action( 'storefront_sidebar' );
get_footer();
